language: python
python:
    - "3.6"
script:
    - coverage run --omit '/home/travis/virtualenv/python3.8.0/lib/*' -m unittest

install:
    - pip install -r requirements.txt

after_success:
    - coveralls